---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install flux cli
      shell: curl -s https://fluxcd.io/install.sh | sudo bash
      become: true
    - name: completion support
      shell: source <(flux completion zsh)
      args:
        executable: /usr/bin/zsh
