---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install htop
      package:
        name: htop
    - name: install flux cli
      command: yay -Sy flux-bin
      become: true
